#!/usr/bin/python
from baselib import *

u = 0.4
n = 15
alpha = n * (n - 1)/2.0  * u
fixval = {"size"   :     n    ,
          "steps"  :   100*40000    , #000 ,
          "burn"   :   100*40000    , #000 ,
          "anneal" :     1*40000    , #000 ,
          "beta"   :    10    ,
          "alpha"  : alpha    , 
          "lone"   :     0    }

varval   = ("q", 0.0, 4e-4, 2e-5)
descript = "teste do cacete"
runny = parallelBatch(descript, fixval, varval)
runny.createBatch()
runny.go()
runny.report("teste.dat")
