#!/usr/bin/python

import os
from time import time
from numpy import arange, sqrt, mean
from numpy.random import uniform
import re

showList = lambda x : " ".join(map(str,x))

def doCalculation(alpha, q, beta, size, steps, burn, annealing, lone):
    cmd  = "./authcpp " + " ".join(map(str,[size, steps, burn, annealing, beta, alpha, q, lone]))
    foo = os.popen(cmd)
    output = "".join([line[0:-1] for line in foo])
    res = re.findall("\d+\.\d+|\d+", output)
    return map(float,res)


def cabecalho(q, beta, size, steps, burn, annealing):
    print "# cut: order parameters versus u = 2 alpha/ N(N-1)"
    print "# size: " , size
    print "# beta: " , beta
    print "# q: "    , q
    print "# steps: ", steps
    print "# burn: " , burn
    print "# anneal: ", annealing
    
if __name__ == "__main__":
    size = 10
    steps = 1000
    burn = 10000
    annealing = 10000
    beta = 10
    q = 0
    u = 0.0
    cabecalho(q, beta, size, steps, burn, annealing)
    while u < 2.0:
        u += 0.01
        alpha = size * (size - 1.0)/2.0 * u
        t = time()
        foo = doCalculation(alpha, q, beta, size, steps, burn, annealing, 1)
        print u, alpha, showList(foo), time() - t
        
        



